# Generated by Django 3.2.15 on 2022-11-06 06:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest_app', '0002_auto_20221106_1224'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='seller_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seller_product', to=settings.AUTH_USER_MODEL),
        ),
    ]
