# Generated by Django 3.2.15 on 2022-11-06 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_app', '0005_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
