# Generated by Django 3.2.15 on 2022-11-06 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_app', '0006_products_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
